### ISSUE TITLE
Incorrect Max Guess Count and Loss Processing

### ISSUE THREAD

**Issue by TheVanadium** [pavo-etc/minecraftle#18]
There should be 10 guesses before the player loses, but the player gets 11.
If the player guesses correctly on the eleventh guess, they receive 2 loss messages.
![image](https://github.com/pavo-etc/minecraftle/assets/53013571/f5f589d1-dc30-418f-8fe2-f2fc181c4af1)

**Comment by pavo-etc** [comment]
This would be from my dodgy fix to #15

**Comment by TheVanadium** [comment]
I'm working on a fix right now, probably going to do things like extract guess count processing to its own function instead of having different functions for the component and integrating the count into the guess correctness processing
If you'd like, it might be helpful to "assign" it to me on GitHub, but I'll get it done at the same completion pace regardless
