### ISSUE TITLE
High Contrast Emoji Summary

### ISSUE THREAD

**Issue by TheVanadium** [pavo-etc/minecraftle#20]
There's no high-contrast version of the emoji summary, and I think it would be relatively simple to make. 
Is the lack of a high-contrast version of the emoji summary a bug, an oversight, or an intentionally omitted feature?
![image](https://github.com/pavo-etc/minecraftle/assets/53013571/33b9077b-2e5e-4d90-979c-2f988e8498a1)

**Comment by pavo-etc** [comment]
Oversight, the high contrast mode was added a year later than the rest of the project
