### ISSUE TITLE
High Contrast Mode Inconsistent w/ NYT

### ISSUE THREAD

**Issue by TheVanadium** [pavo-etc/minecraftle#22]
In NYT's Wordle, in high contrast mode, blue signifies a correct item with an incorrect location, while orange signifies a correct item and location. However, in Minecraftle, it's the reverse. Should we change the app to be consistent with NYT's color scheme?

<img src="https://github.com/pavo-etc/minecraftle/assets/53013571/549d894d-2b7c-47b7-82eb-a6eac3a04b53" alt="Screenshot of correct Minecraftle" width="200" height="275">
<img src="https://github.com/pavo-etc/minecraftle/assets/53013571/9e812440-1588-4ea5-be05-5a489339ed26" alt="NYT Wordle How To Play" width="200" height="250">

**Comment by pavo-etc** [comment]
While I personally think the blue looks better for correct guesses, it would be jarring for people who use the NYT colors so this makes sense. We should change to match them
