### ISSUE TITLE
Rewrite the whole thing in React

### ISSUE THREAD

**Issue by pavo-etc** [pavo-etc/minecraftle#31]
I'm rewriting the whole thing!  Now it won't be so shitty

**Comment by pavo-etc** [comment]
It started off just wanting to switch to a real db so that it wasn't so slow but now I'm doing a full reqrite with next.js

**Comment by pavo-etc** [comment]
It'll be faster!

**Comment by pavo-etc** [comment]
Currently its working well.  TODOS:

- [ ] Show colored slots in the inventory
- [ ] how to play screen
- [ ] music playing
- [ ] automated database migrations

**Comment by pavo-etc** [comment]
Currently everything is working except the basic database schema is becoming a problem. User rank is being calculated by querying for 700k users ranks, and having the server filter that. Definitely too slow, I'm to used to dealing with bigquery solving all my problems.

Considering a wider database structure instead of having a single table record all games played with 1M+ records.

Could do something like:

```prisma
model user {
  id             Int       @id @default(autoincrement())
  user_id        String    @unique
  last_game      DateTime?
}

model game_counts {
  id          Int    @id @default(autoincrement())
  user_id     String
  attempts    Int
  games_count Int
}

```

Each user would have only 11 records max in game_counts (1 record per number of attempts, and then 1 record for number of losses).
Can then just sum up total number of wins and attempts.  Would only record the most recent game timestamp.

**Comment by pavo-etc** [comment]
Test env for this is running on https://staging.minecraftle.zachmanson.com

Works perfectly with small number of games because of my cheap hacks. Currently the database is loaded with a snapshot of the existing minecraftle db, and the stats page crashes.

**Comment by Siiiimon** [comment]
Hey Zach!
I've wanted to contribute to this project for a bit now and just came across this issue thread.
Just wondering if you're open for contributions at all? I might be able to help out with the react rewrite :)

**Comment by TheVanadium** [comment]
> Test env for this is running on https://staging.minecraftle.zachmanson.com
> 
> Works perfectly with small number of games because of my cheap hacks. Currently the database is loaded with a snapshot of the existing minecraftle db, and the stats page crashes.

Will this test environment be made available to other developers? It's not at the moment.

**Comment by pavo-etc** [comment]
@Siiiimon I appreciate you reaching out! The rewrite is nearly complete, only needing the database changes I put in the earlier post, which I would prefer to do myself since it will involve manually fucking with the deployed database.  I'm currently on holiday until early January so won't be able to work on that till I get home. Once I've finished that I would appreciate others testing it and noting any bugs they find, I'm sure I missed a few things when recreating it.  Until then though there's not any specific tasks I need help with.

**Comment by pavo-etc** [comment]
> Will this test environment be made available to other developers? It's not at the moment.

@TheVanadium I will make the test environment public once I've fixed the database  problems

**Comment by Siiiimon** [comment]
> @Siiiimon I appreciate you reaching out! The rewrite is nearly complete, only needing the database changes I put in the earlier post, which I would prefer to do myself since it will involve manually fucking with the deployed database. I'm currently on holiday until early January so won't be able to work on that till I get home. Once I've finished that I would appreciate others testing it and noting any bugs they find, I'm sure I missed a few things when recreating it. Until then though there's not any specific tasks I need help with.

Sounds good! Thanks for taking the time to reply during your holidays. I'm down to test things out when the time comes and I'll keep an eye on the issues :)

**Comment by pavo-etc** [comment]
Here is the a public link to the staging environment.

Seems to be working, but would if anyone could test it.  Leave any issues in this thread.

https://minecraftle-git-real-db-pavo-etc.vercel.app/?_vercel_share=mSJLlSOkUdb3l47wsFVHR6RkcYmthjgR

**Comment by pavo-etc** [comment]
@Siiiimon @TheVanadium
