### ISSUE TITLE
We can see the materials for crafting with the console

### ISSUE THREAD

**Issue by EnzoGH0001** [pavo-etc/minecraftle#8]
When we make a craft, on the console it tells us all the materials that we must use for the craft to guess
![image](https://github.com/pavo-etc/minecraftle/assets/108761778/d882d0fd-9b17-4f62-818f-b6a17bc652cb)
![image](https://github.com/pavo-etc/minecraftle/assets/108761778/247cb7ac-fdcc-46d6-8d57-3ae47dc2d6ae)

**Comment by pavo-etc** [comment]
If you scroll even higher it says exactly what the solution is as the first output from the console

**Comment by pavo-etc** [comment]
I've removed the offending log messages, though there's easy way to hide what the solution is without doing an annoying amount of obfuscation, if someone is willing to use inspect element then that's effectively cheating.  Though at least now they'll need to know how to write JS.
